### ISSUE TITLE
Implementation of FWSVD Baseline ?

### ISSUE THREAD

**Issue by mayank64ce** [hahnyuan/ASVD4LLM#4]
Hello, thank you for the interesting work.

According to this issue [here](https://github.com/AIoT-MLSys-Lab/SVD-LLM/issues/11), this repo also has implementation for the FWSVD baseline. 

I am interested in testing this out. Can you please let me know where can I find it in this repo ?

Thanks

**Comment by sidhantls** [comment]
@mayank64ce FWSVD is also implemented in addition to ASVD. Using `--scaling_method=fisher` when running asvd.py should work. 

https://github.com/hahnyuan/ASVD4LLM/blob/863042743edb4c0dcc512a45534dea07df16b140/asvd.py#L36

**Comment by mayank64ce** [comment]
Oh thanks! Closing the issue.
