### ISSUE TITLE
Errors in the ASVD paper (v3)

### ISSUE THREAD

**Issue by ArtemBiliksin** [hahnyuan/ASVD4LLM#5]
Hello! I found some errors in the ASVD (v3) paper.

**1.** There is an error in the SVD submission. The correct way is: $W = U \mathbf{\Sigma} V^T$.
There is also an unnecessary closing bracket here.
![image](https://github.com/user-attachments/assets/55165040-bf61-4ade-b5c6-7ca6785d7f3b)

**2.** There is an error in the representation of $W_k$. The correct way is: $W_k = U_k \Sigma_k V_k^T$.
  
![image](https://github.com/user-attachments/assets/9d8b51ea-f960-4e4f-91f6-cdf205f3805b)

**3.** It should be like this here $\arg \min_{W_k}\mathcal{L}(W_k) = \arg \min_{W_k} || W_kX- WX ||$ or this $\arg \min_{W_k}\mathcal{L}(W_k) = || W_k^*X- WX ||$.

![image](https://github.com/user-attachments/assets/cbc12777-2a0c-4406-b91b-556cf7e42291)

**4.** You need to bold the characters here because the characters below are bolded.

![image](https://github.com/user-attachments/assets/65e13e10-6701-472f-ab47-2be8d260f1bd)

**5.** The symbol S needs to be bolded because in the statement it is the matrix that is bolded.

![image](https://github.com/user-attachments/assets/93d2d95b-0d6f-4e0b-88d6-d8a62d6b3210)

**Comment by hahnyuan** [comment]
Hi there!
﻿
Thank you for bringing these errors to our attention. We appreciate your review of the ASVD paper! We will make these updates on arxiv paper. You may see the updated arxiv paper tomorrow.

**Comment by ArtemBiliksin** [comment]
Hi! I see there's a new version of the article. Thanks for your work!
